name: S3 Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: npm install
    - name: Run tests
      run: npm test
      
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend/farm_volunteers

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-region: eu-west-2

      - name: Build application
        run: |
          npm install
          npm run build

      - name: Sync build folder to S3
        run: |
          aws s3 sync build/ s3://city-farm