name: S3 Deployment

on:
  push:
    branches:
      - aws-s3-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/farm_volunteers  # Adjusted path

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.3  # Use the latest version of actions/checkout

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-region: eu-west-2

      - name: Build Application
        run: |
          npm ci  # Use npm ci for more deterministic dependency installation
          npm run build

      - name: Sync Build Folder to S3
        run: |
          aws s3 sync build/ s3://city-farm
